### ISSUE TITLE
CEPXS-BFP-LOBATTO not working

### ISSUE THREAD

**Issue by Ahmed-Naceur** [Ahmed-Naceur/dragon5#8]
NOT ABLE TO RUN ANY EXAMPLE.
./RUNCEPXS.sh W_6MeV_50e_50ph_CSD_P15.dat
rm: impossible de supprimer « xslib »: Aucun fichier ou dossier de ce type

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7F3149F386D7
#1  0x7F3149F38D1E
#2  0x7F31494333FF
#3  0x7F3149554300
#4  0x7F314A003AD3
#5  0x4293DC in readin_
#6  0x42CD8B in MAIN__ at CEPXS.f:?
./RUNCEPXS.sh : ligne 8 : 19404 Erreur de segmentation  (core dumped)./CEPXS﻿

**Comment by Ahmed-Naceur** [comment]
Resolved. Now working. Better to add a delete line for "**.fork**" files.

**Comment by Ahmed-Naceur** [comment]
@Ahmed-Naceur: The folder is now cleaned. Running are now located in a new data file. 
Note: if new the code is newly compiled, copy the new CEPXS to the data folder.
